version: '3.3'
services:
  rabbitmq-node:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-node'
    ports:
        - 5672:5672
        - 15672:15672
  mongodb-node:
    image: mongo:6-jammy
    container_name: 'mongodb-node'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo_pass
    ports:
      - '27017:27017'
    volumes:
      - "./data:/data/db"
  etl-node:
    image: simple-csv-etl
    command: ["/main","csv-etl"]
    # command: ["/go/bin/dlv", "--listen=:4000","--wd=/", "--headless=true", "--log=true", "--accept-multiclient", "--api-version=2", "exec","/main","gateway"]
    container_name: simple-csv-etl-node
    depends_on:
      - rabbitmq-node
    ports:
      - "8080:8080"
      - "4087:4000"
    user: root
    volumes:
      - "$PWD/.config/gateway:/config"
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
